import type { FormSchema } from '@/shared/types'

export const form1FarmerSchema: FormSchema = {
  formCode: '1-фермер',
  title: 'Форма № 1-фермер: Отчет об итогах сева под урожай',
  periodType: 'annual',
  frequency: '1 раз в год (не позднее 10 июня)',
  sections: [
    {
      id: 'sec-winter-crops',
      code: 'I',
      title: '1. Посев озимых культур осенью прошлого года',
      description: 'Данные о площадях посева озимых зерновых культур, озимого рапса и озимых на зеленый корм (в гектарах с одним знаком после запятой).',
      activityGroup: 'crops',
      rows: [
        {
          code: '001',
          title: 'Посеяно озимых на зерно и зеленый корм осенью прошлого года – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '002 + 003 + 004 + 005 + 006',
          hint: 'Авторасчет: сумма строк 002+003+004+005+006',
        },
        { code: '002', title: 'в том числе: пшеница', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '003', title: 'рожь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '004', title: 'ячмень', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '005', title: 'рапс', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '006', title: 'тритикале', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-winter-loss',
      code: 'II',
      title: '2. Гибель, использование и сохранность озимых культур',
      description: 'Сведения о погибших озимых, площадях под зеленый корм и сохранившихся к концу сева яровых.',
      activityGroup: 'crops',
      rows: [
        {
          code: '007',
          title: 'Полностью погибло озимых на зерно и зеленый корм до окончания сева яровых – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '008 + 009 + 010 + 011 + 012',
          hint: 'Авторасчет: сумма строк 008+009+010+011+012',
        },
        { code: '008', title: 'в том числе: пшеница', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '009', title: 'рожь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '010', title: 'ячмень', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '011', title: 'рапс', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '012', title: 'тритикале', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '013',
          title: 'Площадь озимых, использованных на зеленый корм, силос и выпас, на которой произведен посев яровых культур',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
        {
          code: '014',
          title: 'Сохранилось озимых на зерно к концу сева яровых – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '015 + 016 + 017 + 018',
          hint: 'Авторасчет: сумма строк 015+016+017+018',
        },
        { code: '015', title: 'в том числе: пшеница', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '016', title: 'рожь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '017', title: 'ячмень', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '018', title: 'тритикале', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '019',
          title: 'Сохранилось озимых на зеленый корм, силос, для получения гранул, брикетов и выпас, где не производился посев яровых',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
      ],
    },
    {
      id: 'sec-spring-cereals',
      code: 'III',
      title: '3. Яровые зерновые и зернобобовые культуры',
      description: 'Посевы яровых зерновых и зернобобовых культур под урожай текущего года.',
      activityGroup: 'crops',
      rows: [
        {
          code: '020',
          title: 'Яровые зерновые и зернобобовые культуры (включая кукурузу на зерно) – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '021 + 022 + 023 + 024 + 025 + 026 + 027 + 028 + 029 + 030 + 031 + 032 + 033 + 034 + 035',
          hint: 'Авторасчет: сумма строк 021-035',
        },
        { code: '021', title: 'в том числе: пшеница', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '022', title: 'рожь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '023', title: 'ячмень', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '024', title: 'овес', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '025', title: 'кукуруза на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '026', title: 'просо', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '027', title: 'гречиха', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '028', title: 'горох', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '029', title: 'фасоль', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '030', title: 'чечевица', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '031', title: 'вика и смеси виковые на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '032', title: 'нут', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '033', title: 'прочие зернобобовые', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '034', title: 'сорго на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '035', title: 'прочие яровые зерновые на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-tech-crops',
      code: 'IV',
      title: '4. Технические культуры',
      description: 'Подсолнечник, соя, рапс, лен, горчица, лекарственные и эфиромасличные культуры.',
      activityGroup: 'crops',
      rows: [
        {
          code: '039',
          title: 'Технические культуры – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '040 + 042 + 043 + 044 + 045 + 046 + 047 + 048 + 049 + 050 + 055 + 060',
          hint: 'Авторасчет: сумма строк 040-060',
        },
        { code: '040', title: 'в том числе: сахарная свекла', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '042', title: 'подсолнечник кондитерский', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '043', title: 'подсолнечник масличный', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '044', title: 'лён', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '045', title: 'соя', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '046', title: 'горчица', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '047', title: 'рапс озимый (сохранившаяся площадь)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '048', title: 'рапс яровой', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '049', title: 'редька масличная', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '050', title: 'лекарственные культуры', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '055', title: 'эфиромасличные культуры (лаванда, шалфей и др.)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '060', title: 'прочие технические культуры', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-vegetables-potatoes',
      code: 'V',
      title: '5. Картофель, овощи и бахчевые культуры',
      description: 'Картофель, овощи открытого грунта по видам, бахча и семенники.',
      activityGroup: 'crops',
      rows: [
        {
          code: '062',
          title: 'Картофель, овощи и бахчевые культуры – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '063 + 066 + 085 + 090 + 092',
          hint: 'Авторасчет: сумма строк 063+066+085+090+092',
        },
        { code: '063', title: 'Картофель', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '066',
          title: 'Овощи открытого грунта – всего (сумма строк с 067 по 080)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '067 + 068 + 069 + 070 + 071 + 072 + 073 + 074 + 075 + 076 + 077 + 078 + 079 + 080',
          hint: 'Авторасчет: сумма овощных культур 067-080',
          indent: 1,
        },
        { code: '067', title: 'в том числе: капуста всех видов', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '068', title: 'огурцы', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '069', title: 'помидоры', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '070', title: 'свекла столовая', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '071', title: 'морковь столовая', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '072', title: 'лук на репку', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '073', title: 'чеснок', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '074', title: 'зеленый горошек', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '075', title: 'сахарная кукуруза', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '076', title: 'тыква', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '077', title: 'кабачки', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '078', title: 'перец сладкий', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '079', title: 'баклажаны', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '080', title: 'прочие овощи', unit: 'га', valueType: 'number', precision: 1, indent: 2 },
        { code: '085', title: 'Семенники однолетних овощных культур, высадки семенников двухлетних', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '090', title: 'Бахча продовольственная (арбузы и дыни)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '092', title: 'Семенники бахчи продовольственной', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-fodder-spring-total',
      code: 'VI',
      title: '6. Кормовые культуры и яровые всего',
      description: 'Кормовые корнеплоды, силос, травы и общая площадь яровых культур.',
      activityGroup: 'crops',
      rows: [
        {
          code: '093',
          title: 'Кормовые культуры – всего (019+094+098+100+103+109+141)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '019 + 094 + 098 + 100 + 103 + 109 + 141',
          hint: 'Авторасчет: сумма кормовых культур',
        },
        { code: '094', title: 'из них: кормовые корнеплоды и бахчевые культуры', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '098', title: 'кукуруза на кормовые цели', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '100', title: 'культуры кормовые на силос (без кукурузы)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '103', title: 'однолетние травы на сено, семена, зеленый корм, сенаж и выпас', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '109', title: 'многолетние беспокровные травы посева текущего года (без подпокровных)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '114',
          title: 'Яровые культуры (без многолетних трав прошлых лет) – всего (020+039+062+094+098+100+103+109-047)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '020 + 039 + 062 + 094 + 098 + 100 + 103 + 109 - 047',
          hint: 'Авторасчет: 020+039+062+094+098+100+103+109-047',
        },
        { code: '115', title: 'из них: посеяно яровых по погибшим озимым', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '141', title: 'Укосная площадь многолетних трав посевов прошлых лет на сено, силос и выпас', unit: 'га', valueType: 'number', precision: 1 },
      ],
    },
    {
      id: 'sec-total-land-balance',
      code: 'VII',
      title: '7. Общая посевная площадь и сельскохозяйственные угодья',
      description: 'Итоговая посевная площадь, структура пашни, сенокосы, пастбища и пары.',
      activityGroup: 'crops',
      rows: [
        {
          code: '150',
          title: 'ОБЩАЯ ПЛОЩАДЬ ПОСЕВА ОЗИМЫХ И ЯРОВЫХ ПОД УРОЖАЙ (014+019+047+114+141)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '014 + 019 + 047 + 114 + 141',
          hint: 'Авторасчет: 014 + 019 + 047 + 114 + 141',
        },
        { code: '151', title: 'из нее: в междурядьях садов и виноградников', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '152', title: 'предварительных культур на распаханных сенокосах и пастбищах', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '153', title: 'Кроме того, многолетние подпокровные травы (подсев с осени)', unit: 'га', valueType: 'number', precision: 1 },
        {
          code: '160',
          title: 'Площадь сельскохозяйственных угодий – всего (161+162+163)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '161 + 162 + 163',
          hint: 'Авторасчет: сумма пашни (161) + сенокосы (162) + многолетние насаждения (163)',
        },
        {
          code: '161',
          title: 'в том числе: пашня (150 – 151 – 152 + 190)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '150 - 151 - 152 + 190',
          hint: 'Авторасчет: 150 - 151 - 152 + 190',
          indent: 1,
        },
        { code: '162', title: 'сенокосы и пастбища', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '163', title: 'многолетние насаждения (сады, виноградники)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '190',
          title: 'Из стр. 161: незасеянная площадь пашни (чистые пары и др.)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
        { code: '191', title: 'из нее: площадь паров, включая сидеральные', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
  ],
  validationRules: [
    {
      id: 'val-001',
      type: 'formula_equals',
      targetRowCode: '001',
      expression: '002 + 003 + 004 + 005 + 006',
      message: 'Строка 001 (Посеяно озимых всего) должна равняться сумме строк 002+003+004+005+006.',
      severity: 'error',
    },
    {
      id: 'val-007',
      type: 'formula_equals',
      targetRowCode: '007',
      expression: '008 + 009 + 010 + 011 + 012',
      message: 'Строка 007 (Погибло озимых всего) должна равняться сумме строк 008+009+010+011+012.',
      severity: 'error',
    },
    {
      id: 'val-winter-balance',
      type: 'formula_equals',
      targetRowCode: '001',
      expression: '007 + 013 + 014 + 019 + 047',
      message: 'Официальный баланс озимых: стр. 001 должна быть строго равна (007 + 013 + 014 + 019 + 047).',
      severity: 'error',
    },
    {
      id: 'val-020',
      type: 'formula_equals',
      targetRowCode: '020',
      expression: '021 + 022 + 023 + 024 + 025 + 026 + 027 + 028 + 029 + 030 + 031 + 032 + 033 + 034 + 035',
      message: 'Строка 020 (Яровые зерновые всего) должна равняться сумме строк 021-035.',
      severity: 'error',
    },
    {
      id: 'val-039',
      type: 'formula_equals',
      targetRowCode: '039',
      expression: '040 + 042 + 043 + 044 + 045 + 046 + 047 + 048 + 049 + 050 + 055 + 060',
      message: 'Строка 039 (Технические культуры всего) должна равняться сумме строк 040-060.',
      severity: 'error',
    },
    {
      id: 'val-066',
      type: 'formula_equals',
      targetRowCode: '066',
      expression: '067 + 068 + 069 + 070 + 071 + 072 + 073 + 074 + 075 + 076 + 077 + 078 + 079 + 080',
      message: 'Строка 066 (Овощи открытого грунта) должна равняться сумме овощей 067-080.',
      severity: 'error',
    },
    {
      id: 'val-062',
      type: 'formula_equals',
      targetRowCode: '062',
      expression: '063 + 066 + 085 + 090 + 092',
      message: 'Строка 062 (Картофель, овощи и бахча) должна равняться сумме 063+066+085+090+092.',
      severity: 'error',
    },
    {
      id: 'val-093',
      type: 'formula_equals',
      targetRowCode: '093',
      expression: '019 + 094 + 098 + 100 + 103 + 109 + 141',
      message: 'Строка 093 (Кормовые культуры всего) должна равняться сумме 019+094+098+100+103+109+141.',
      severity: 'error',
    },
    {
      id: 'val-114',
      type: 'formula_equals',
      targetRowCode: '114',
      expression: '020 + 039 + 062 + 094 + 098 + 100 + 103 + 109 - 047',
      message: 'Строка 114 (Яровые культуры всего) должна равняться 020+039+062+094+098+100+103+109-047.',
      severity: 'error',
    },
    {
      id: 'val-150',
      type: 'formula_equals',
      targetRowCode: '150',
      expression: '014 + 019 + 047 + 114 + 141',
      message: 'Строка 150 (Общая площадь посева) должна равняться 014+019+047+114+141.',
      severity: 'error',
    },
    {
      id: 'val-160',
      type: 'formula_equals',
      targetRowCode: '160',
      expression: '161 + 162 + 163',
      message: 'Строка 160 (Сельхозугодья всего) должна равняться сумме пашни (161), сенокосов (162) и насаждений (163).',
      severity: 'error',
    },
    {
      id: 'val-161',
      type: 'formula_equals',
      targetRowCode: '161',
      expression: '150 - 151 - 152 + 190',
      message: 'Баланс пашни (стр. 161) должен равняться (150 – 151 – 152 + 190).',
      severity: 'error',
    },
    {
      id: 'val-anom-sown-area',
      type: 'max_decrease_percent',
      targetRowCode: '150',
      expression: '50',
      message: 'Предупреждение: общая посевная площадь снизилась более чем на 50% относительно прошлого года.',
      severity: 'warning',
    },
  ],
}
