import type { FormSchema } from '@/shared/types'

export const form1FarmerSchema: FormSchema = {
  formCode: '1-фермер',
  title: 'Форма № 1-фермер: Отчет об итогах сева под урожай',
  periodType: 'annual',
  frequency: '1 раз в год (до 10 июня)',
  sections: [
    {
      id: 'sec-1',
      code: 'I',
      title: '1. Посев озимых культур осенью прошлого года',
      description: 'Данные о площадях посева озимых зерновых культур, озимого рапса и озимых на зеленый корм (в гектарах).',
      activityGroup: 'crops',
      rows: [
        {
          code: '001',
          title: 'Посеяно озимых на зерно и зеленый корм осенью прошлого года – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '002 + 003 + 004 + 005 + 006',
          hint: 'Рассчитывается автоматически: сумма строк 002-006',
        },
        { code: '002', title: 'в том числе: пшеница озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '003', title: 'ячмень озимый', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '004', title: 'рожь озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '005', title: 'рапс озимый на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '006', title: 'озимые на зеленый корм и силос', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-2',
      code: 'II',
      title: '2. Гибель и использование озимых культур',
      description: 'Сведения о погибших или использованных на корм озимых культурах.',
      activityGroup: 'crops',
      rows: [
        {
          code: '007',
          title: 'Полностью погибло озимых на зерно и зеленый корм до окончания сева яровых – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '008 + 009 + 010 + 011 + 012',
          hint: 'Рассчитывается автоматически: сумма строк 008-012',
        },
        { code: '008', title: 'в том числе: пшеница озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '009', title: 'ячмень озимый', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '010', title: 'рожь озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '011', title: 'рапс озимый на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '012', title: 'озимые на зеленый корм и силос', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '013',
          title: 'Площадь озимых, использованных на зеленый корм, силос и выпас, на которой произведен посев яровых',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
        {
          code: '014',
          title: 'Сохранилось озимых на зерно к концу сева яровых – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '015 + 016 + 017 + 018',
          hint: 'Рассчитывается автоматически: сумма строк 015-018',
        },
        { code: '015', title: 'в том числе: пшеница озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '016', title: 'ячмень озимый', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '017', title: 'рожь озимая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '018', title: 'рапс озимый на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-3',
      code: 'III',
      title: '3. Посев яровых культур (зерновые, технические, овощи)',
      description: 'Фактические размеры посевов яровых культур под урожай текущего года.',
      activityGroup: 'crops',
      rows: [
        {
          code: '020',
          title: 'Яровые зерновые и зернобобовые культуры (включая кукурузу на зерно) – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '021 + 022 + 023 + 024 + 025 + 026 + 027 + 033',
          hint: 'Авторасчет: сумма яровых зерновых',
        },
        { code: '021', title: 'в том числе: пшеница яровая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '022', title: 'ячмень яровой', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '023', title: 'овес', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '024', title: 'кукуруза на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '025', title: 'просо', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '026', title: 'гречиха', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '027', title: 'сорго на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '033', title: 'зернобобовые культуры (горох, фасоль, нут и др.)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '039',
          title: 'Технические культуры – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '040 + 043 + 045 + 050 + 055',
          hint: 'Авторасчет: сумма технических культур',
        },
        { code: '040', title: 'из них: подсолнечник на зерно', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '043', title: 'соя', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '045', title: 'рапс яровой (кольза)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '050', title: 'лекарственные культуры', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '055', title: 'эфиромасличные культуры (лаванда, шалфей и др.)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '063', title: 'Картофель', unit: 'га', valueType: 'number', precision: 1 },
        {
          code: '066',
          title: 'Овощи открытого грунта – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '067 + 068 + 069 + 070 + 071 + 072 + 073 + 074 + 078 + 079 + 080',
          hint: 'Авторасчет: сумма овощных культур',
        },
        { code: '067', title: 'в том числе: капуста всех видов', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '068', title: 'огурцы', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '069', title: 'помидоры', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '070', title: 'свекла столовая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '071', title: 'морковь столовая', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '072', title: 'лук на репку', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '073', title: 'чеснок', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '074', title: 'зеленый горошек', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '078', title: 'перец сладкий', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '079', title: 'баклажаны', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '080', title: 'прочие овощи', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '090', title: 'Бахча продовольственная (арбузы и дыни)', unit: 'га', valueType: 'number', precision: 1 },
      ],
    },
    {
      id: 'sec-4',
      code: 'IV',
      title: '4. Кормовые культуры и итоги сева яровых',
      description: 'Однолетние, многолетние травы, силос и общая площадь яровых.',
      activityGroup: 'crops',
      rows: [
        {
          code: '093',
          title: 'Кормовые культуры – всего',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '094 + 098 + 100 + 103 + 109',
          hint: 'Авторасчет: сумма кормовых культур',
        },
        { code: '094', title: 'из них: кормовые корнеплоды и бахчевые', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '098', title: 'кукуруза на кормовые цели (силос, зеленый корм)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '100', title: 'культуры кормовые на силос (без кукурузы)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '103', title: 'однолетние травы на сено, зеленый корм и выпас', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '109', title: 'многолетние беспокровные травы посева текущего года', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '114',
          title: 'Яровые культуры под урожай текущего года – ВСЕГО',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '020 + 039 + 063 + 066 + 090 + 093',
          hint: 'Сумма: зерновые (020) + технические (039) + картофель (063) + овощи (066) + бахча (090) + кормовые (093)',
        },
        {
          code: '141',
          title: 'Укосная площадь многолетних трав посевов прошлых лет',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
      ],
    },
    {
      id: 'sec-5',
      code: 'V',
      title: '5. Итоги посева и баланс сельскохозяйственных угодий',
      description: 'Общая посевная площадь, пашня, сенокосы, пастбища и незасеянные площади.',
      activityGroup: 'crops',
      rows: [
        {
          code: '150',
          title: 'ОБЩАЯ ПЛОЩАДЬ ПОСЕВА (озимые сохранившиеся + яровые + многолетние травы)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '014 + 114 + 141',
          hint: 'Рассчитывается автоматически: 014 + 114 + 141',
        },
        {
          code: '160',
          title: 'Площадь сельскохозяйственных угодий – ВСЕГО',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '161 + 162 + 163',
          hint: 'Рассчитывается: пашня (161) + сенокосы (162) + многолетние насаждения (163)',
        },
        {
          code: '161',
          title: 'в том числе: пашня',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          hint: 'Фактическая площадь пашни хозяйства',
          indent: 1,
        },
        { code: '162', title: 'сенокосы и пастбища', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '163', title: 'многолетние насаждения (сады, виноградники)', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        {
          code: '190',
          title: 'Из стр. 161 (пашня) – незасеянная площадь пашни (чистые пары и др.)',
          unit: 'га',
          valueType: 'number',
          precision: 1,
        },
      ],
    },
  ],
  validationRules: [
    {
      id: 'val-001',
      type: 'formula_equals',
      targetRowCode: '001',
      expression: '002 + 003 + 004 + 005 + 006',
      message: 'Строка 001 (Всего посеяно озимых) должна быть равна сумме строк 002+003+004+005+006.',
      severity: 'error',
    },
    {
      id: 'val-007',
      type: 'formula_equals',
      targetRowCode: '007',
      expression: '008 + 009 + 010 + 011 + 012',
      message: 'Строка 007 (Погибло озимых) должна быть равна сумме строк 008+009+010+011+012.',
      severity: 'error',
    },
    {
      id: 'val-winter-check',
      type: 'formula_equals',
      targetRowCode: '001',
      expression: '007 + 013 + 014',
      message: 'Баланс озимых: строка 001 (посеяно озимых) должна равняться сумме погибших (007), использованных (013) и сохранившихся (014).',
      severity: 'error',
    },
    {
      id: 'val-114',
      type: 'formula_equals',
      targetRowCode: '114',
      expression: '020 + 039 + 063 + 066 + 090 + 093',
      message: 'Строка 114 (Яровые всего) должна равняться сумме строк 020+039+063+066+090+093.',
      severity: 'error',
    },
    {
      id: 'val-150',
      type: 'formula_equals',
      targetRowCode: '150',
      expression: '014 + 114 + 141',
      message: 'Строка 150 (Общая площадь посева) должна равняться сумме сохранившихся озимых (014), яровых (114) и укосных трав (141).',
      severity: 'error',
    },
    {
      id: 'val-161-arable',
      type: 'formula_gte',
      targetRowCode: '161',
      expression: '150 + 190',
      message: 'Площадь пашни (стр. 161) не может быть меньше суммы всей засеянной площади (стр. 150) и паров (стр. 190).',
      severity: 'warning',
    },
    {
      id: 'val-anom-150',
      type: 'max_decrease_percent',
      targetRowCode: '150',
      expression: '50',
      message: 'Внимание: общая посевная площадь снизилась более чем на 50% по сравнению с прошлым годом.',
      severity: 'warning',
    },
  ],
}
