import type { FormSchema } from '@/shared/types'

export const form3FarmerSchema: FormSchema = {
  formCode: '3-фермер',
  title: 'Форма № 3-фермер: Отчет о производстве продукции животноводства и численности скота',
  periodType: 'annual',
  frequency: 'Годовая / Ежеквартальная (до 15 января / до 5 числа после квартала)',
  submissionDeadline: { month: 1, day: 15, yearOffset: 1 },
  sections: [
    {
      id: 'sec-livestock-count',
      code: 'I',
      title: '1. Наличие и поголовье сельскохозяйственных животных',
      description: 'Численность скота и птицы в хозяйстве на отчетную дату (в головах).',
      activityGroup: 'livestock',
      rows: [
        { code: '010', title: 'Крупный рогатый скот (КРС) – ВСЕГО', unit: 'голов', valueType: 'integer' },
        { code: '011', title: 'в том числе: коровы молочного и мясного стада', unit: 'голов', valueType: 'integer', indent: 1 },
        { code: '012', title: 'нетели и телки от 1 года до 2 лет', unit: 'голов', valueType: 'integer', indent: 1 },
        { code: '020', title: 'Свиньи – ВСЕГО', unit: 'голов', valueType: 'integer' },
        { code: '021', title: 'в том числе: основные свиноматки', unit: 'голов', valueType: 'integer', indent: 1 },
        { code: '030', title: 'Овцы и козы – ВСЕГО', unit: 'голов', valueType: 'integer' },
        { code: '031', title: 'в том числе: овцематки и козоматки от 1 года и старше', unit: 'голов', valueType: 'integer', indent: 1 },
        { code: '040', title: 'Лошади – ВСЕГО', unit: 'голов', valueType: 'integer' },
        { code: '041', title: 'в том числе: кобылы от 3 лет и старше', unit: 'голов', valueType: 'integer', indent: 1 },
        { code: '050', title: 'Птица всех видов – ВСЕГО', unit: 'голов', valueType: 'integer' },
        { code: '051', title: 'в том числе: куры-несушки', unit: 'голов', valueType: 'integer', indent: 1 },
      ],
    },
    {
      id: 'sec-livestock-production',
      code: 'II',
      title: '2. Производство (выращивание) скота и птицы',
      description: 'Приплод молодняка, прирост живой массы и сохранность поголовья.',
      activityGroup: 'livestock',
      rows: [
        { code: '060', title: 'Получено живого приплода телят', unit: 'голов', valueType: 'integer' },
        { code: '061', title: 'Получено живого приплода поросят', unit: 'голов', valueType: 'integer' },
        { code: '062', title: 'Получено живого приплода ягнят и козлят', unit: 'голов', valueType: 'integer' },
        { code: '070', title: 'Получено прироста (выращивание скота и птицы в живой массе) – всего', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '080', title: 'Падеж и гибель скота и птицы всех видов', unit: 'голов', valueType: 'integer' },
      ],
    },
    {
      id: 'sec-dairy-poultry',
      code: 'III',
      title: '3. Производство продукции животноводства',
      description: 'Валовой надой молока, производство яиц, настриг шерсти и мед.',
      activityGroup: 'livestock',
      rows: [
        { code: '100', title: 'Надоено молока сырого коровьего – всего', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '110', title: 'Получено яиц куриных от всех видов птицы – всего', unit: 'тыс. шт', valueType: 'number', precision: 1 },
        { code: '120', title: 'Настрижено шерсти овечьей в физическом весе', unit: 'кг', valueType: 'number', precision: 1 },
        { code: '130', title: 'Получено товарного меда', unit: 'кг', valueType: 'number', precision: 1 },
      ],
    },
    {
      id: 'sec-livestock-sales',
      code: 'IV',
      title: '4. Реализация основных продуктов животноводства',
      description: 'Продажа скота на убой (в живом весе), реализация молока и яиц переработчикам и на рынке.',
      activityGroup: 'livestock',
      rows: [
        {
          code: '160',
          title: 'Продано скота и птицы на убой (в живом весе) – ВСЕГО',
          unit: 'ц',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '161 + 162 + 163 + 164',
          hint: 'Авторасчет: сумма строк 161+162+163+164',
        },
        { code: '161', title: 'в том числе: крупный рогатый скот (КРС)', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '162', title: 'свиньи', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '163', title: 'овцы и козы', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '164', title: 'птица всех видов', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '170', title: 'Продано молока и молочных продуктов (в пересчете на молоко)', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '180', title: 'Продано яиц пищевых', unit: 'тыс. шт', valueType: 'number', precision: 1 },
      ],
    },
  ],
  validationRules: [
    {
      id: 'val-cows-lte-cattle',
      type: 'formula_gte',
      targetRowCode: '010',
      expression: '011 + 012',
      message: 'Общее поголовье КРС (стр. 010) не может быть меньше суммы коров (011) и нетелей/телок (012).',
      severity: 'error',
    },
    {
      id: 'val-sows-lte-pigs',
      type: 'formula_gte',
      targetRowCode: '020',
      expression: '021',
      message: 'Общее поголовье свиней (стр. 020) не может быть меньше количества основных свиноматок (021).',
      severity: 'error',
    },
    {
      id: 'val-ewes-lte-sheep',
      type: 'formula_gte',
      targetRowCode: '030',
      expression: '031',
      message: 'Поголовье овец и коз (стр. 030) не может быть меньше маточного поголовья (031).',
      severity: 'error',
    },
    {
      id: 'val-hens-lte-poultry',
      type: 'formula_gte',
      targetRowCode: '050',
      expression: '051',
      message: 'Общее поголовье птицы (стр. 050) не может быть меньше кур-несушек (051).',
      severity: 'error',
    },
    {
      id: 'val-sales-meat-sum',
      type: 'formula_equals',
      targetRowCode: '160',
      expression: '161 + 162 + 163 + 164',
      message: 'Строка 160 (Реализация скота на убой всего) должна равняться сумме строк 161+162+163+164.',
      severity: 'error',
    },
  ],
}
