import type { FormSchema } from '@/shared/types'

export const form2FarmerSchema: FormSchema = {
  formCode: '2-фермер',
  title: 'Форма № 2-фермер: Сбор урожая сельскохозяйственных культур',
  periodType: 'annual',
  frequency: '1 раз в год (до 1 декабря)',
  sections: [
    {
      id: 'sec-harvest-grain',
      code: 'I',
      title: '1. Сбор урожая зерновых и зернобобовых культур',
      description: 'Фактически убранная площадь (га) и валовой сбор (центнеров) в первоначально оприходованном весе.',
      activityGroup: 'crops',
      rows: [
        {
          code: '100',
          title: 'Зерновые и зернобобовые культуры – УБРАННАЯ ПЛОЩАДЬ, ВСЕГО',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '102 + 104 + 106 + 108 + 110 + 112 + 114 + 116 + 118',
          hint: 'Авторасчет: сумма убранных площадей зерновых культур',
        },
        {
          code: '101',
          title: 'Зерновые и зернобобовые культуры – ВАЛОВОЙ СБОР, ВСЕГО',
          unit: 'ц',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '103 + 105 + 107 + 109 + 111 + 113 + 115 + 117 + 119',
          hint: 'Авторасчет: сумма валового сбора зерновых культур',
        },
        { code: '102', title: 'в т.ч. Пшеница озимая и яровая – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '103', title: 'Пшеница озимая и яровая – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '104', title: 'Ячмень озимый и яровой – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '105', title: 'Ячмень озимый и яровой – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '106', title: 'Кукуруза на зерно – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '107', title: 'Кукуруза на зерно – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '108', title: 'Рожь озимая и яровая – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '109', title: 'Рожь озимая и яровая – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '110', title: 'Овес – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '111', title: 'Овес – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '112', title: 'Гречиха – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '113', title: 'Гречиха – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '114', title: 'Горох на зерно – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '115', title: 'Горох на зерно – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '116', title: 'Нут – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '117', title: 'Нут – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '118', title: 'Сорго на зерно и прочие зерновые – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '119', title: 'Сорго на зерно и прочие зерновые – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-harvest-tech',
      code: 'II',
      title: '2. Сбор урожая технических культур',
      description: 'Подсолнечник, соя, рапс, лен, горчица, сахарная свекла и эфиромасличные.',
      activityGroup: 'crops',
      rows: [
        {
          code: '200',
          title: 'Технические культуры – УБРАННАЯ ПЛОЩАДЬ, ВСЕГО',
          unit: 'га',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '202 + 204 + 206 + 208 + 210 + 212',
          hint: 'Авторасчет: сумма площадей технических культур',
        },
        {
          code: '201',
          title: 'Технические культуры – ВАЛОВОЙ СБОР, ВСЕГО',
          unit: 'ц',
          valueType: 'number',
          precision: 1,
          isCalculated: true,
          calculationFormula: '203 + 205 + 207 + 209 + 211 + 213',
          hint: 'Авторасчет: сумма валового сбора технических культур',
        },
        { code: '202', title: 'в т.ч. Подсолнечник (масличный и кондитерский) – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '203', title: 'Подсолнечник – валовой сбор семян', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '204', title: 'Соя – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '205', title: 'Соя – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '206', title: 'Рапс озимый и яровой – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '207', title: 'Рапс озимый и яровой – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '208', title: 'Лён масличный – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '209', title: 'Лён масличный – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '210', title: 'Горчица – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '211', title: 'Горчица – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '212', title: 'Эфиромасличные и лекарственные культуры – убранная площадь', unit: 'га', valueType: 'number', precision: 1, indent: 1 },
        { code: '213', title: 'Эфиромасличные и лекарственные культуры – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
      ],
    },
    {
      id: 'sec-harvest-veg-orchard',
      code: 'III',
      title: '3. Овощи, картофель, сады и виноградники',
      description: 'Картофель, овощи открытого грунта, защищенный грунт, косточковые/семечковые сады и виноградники.',
      activityGroup: 'crops',
      rows: [
        { code: '300', title: 'Картофель – убранная площадь', unit: 'га', valueType: 'number', precision: 1 },
        { code: '301', title: 'Картофель – валовой сбор', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '302', title: 'Овощи открытого грунта – убранная площадь, всего', unit: 'га', valueType: 'number', precision: 1 },
        { code: '303', title: 'Овощи открытого грунта – валовой сбор, всего', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '304', title: 'в т.ч. Помидоры (томаты) – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '305', title: 'Огурцы – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '306', title: 'Капуста всех видов – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '307', title: 'Лук на репку и чеснок – валовой сбор', unit: 'ц', valueType: 'number', precision: 1, indent: 1 },
        { code: '308', title: 'Бахча продовольственная (арбузы, дыни) – валовой сбор', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '310', title: 'Теплицы и парники (защищенный грунт) – сбор овощей', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '320', title: 'Плодово-ягодные насаждения (сады) – площадь в плодоносящем возрасте', unit: 'га', valueType: 'number', precision: 1 },
        { code: '321', title: 'Плоды семечковые и косточковые (яблоки, сливы, персики) – валовой сбор', unit: 'ц', valueType: 'number', precision: 1 },
        { code: '330', title: 'Виноградники – площадь в плодоносящем возрасте', unit: 'га', valueType: 'number', precision: 1 },
        { code: '331', title: 'Виноград столовый и технический – валовой сбор', unit: 'ц', valueType: 'number', precision: 1 },
      ],
    },
  ],
  validationRules: [
    {
      id: 'val-grain-area-sum',
      type: 'formula_equals',
      targetRowCode: '100',
      expression: '102 + 104 + 106 + 108 + 110 + 112 + 114 + 116 + 118',
      message: 'Строка 100 (Убранная площадь зерновых) должна быть равна сумме убранных площадей по видам культур.',
      severity: 'error',
    },
    {
      id: 'val-grain-yield-sum',
      type: 'formula_equals',
      targetRowCode: '101',
      expression: '103 + 105 + 107 + 109 + 111 + 113 + 115 + 117 + 119',
      message: 'Строка 101 (Валовой сбор зерновых) должен быть равен сумме валового сбора по культурам.',
      severity: 'error',
    },
    {
      id: 'val-tech-area-sum',
      type: 'formula_equals',
      targetRowCode: '200',
      expression: '202 + 204 + 206 + 208 + 210 + 212',
      message: 'Строка 200 (Убранная площадь технических культур) должна быть равна сумме площадей по видам.',
      severity: 'error',
    },
    {
      id: 'val-tech-yield-sum',
      type: 'formula_equals',
      targetRowCode: '201',
      expression: '203 + 205 + 207 + 209 + 211 + 213',
      message: 'Строка 201 (Валовой сбор технических культур) должен быть равен сумме сбора по культурам.',
      severity: 'error',
    },
  ],
}
